//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.11 at 02:35:40 PM GST 
//


package com.adcb.ocr.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtractMRZRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtractMRZRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="imgEncodedFP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="imgEncodedBP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="docType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtractMRZRequest", propOrder = {
    "cid",
    "imgEncodedFP",
    "imgEncodedBP",
    "docType"
})
@XmlRootElement(name="ExtractMRZRequest")
public class ExtractMRZRequest {

    protected String cid;
    protected String imgEncodedFP;
    protected String imgEncodedBP;
    protected String docType;

    /**
     * Gets the value of the cid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCid() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCid(String value) {
        this.cid = value;
    }

    /**
     * Gets the value of the imgEncodedFP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgEncodedFP() {
        return imgEncodedFP;
    }

    /**
     * Sets the value of the imgEncodedFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgEncodedFP(String value) {
        this.imgEncodedFP = value;
    }

    /**
     * Gets the value of the imgEncodedBP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgEncodedBP() {
        return imgEncodedBP;
    }

    /**
     * Sets the value of the imgEncodedBP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgEncodedBP(String value) {
        this.imgEncodedBP = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocType(String value) {
        this.docType = value;
    }

}
