//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.11 at 02:35:40 PM GST 
//


package com.adcb.ocr.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adcb.ocr.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExtractMRZResponse_QNAME = new QName("http://adcb.com/ocr/providers/ExtractMRZ", "ExtractMRZResponse");
    private final static QName _ExtractMRZRequest_QNAME = new QName("http://adcb.com/ocr/providers/ExtractMRZ", "ExtractMRZRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adcb.ocr.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtractMRZResponse }
     * 
     */
    public ExtractMRZResponse createExtractMRZResponse() {
        return new ExtractMRZResponse();
    }

    /**
     * Create an instance of {@link ExtractMRZRequest }
     * 
     */
    public ExtractMRZRequest createExtractMRZRequest() {
        return new ExtractMRZRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtractMRZResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adcb.com/ocr/providers/ExtractMRZ", name = "ExtractMRZResponse")
    public JAXBElement<ExtractMRZResponse> createExtractMRZResponse(ExtractMRZResponse value) {
        return new JAXBElement<ExtractMRZResponse>(_ExtractMRZResponse_QNAME, ExtractMRZResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtractMRZRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://adcb.com/ocr/providers/ExtractMRZ", name = "ExtractMRZRequest")
    public JAXBElement<ExtractMRZRequest> createExtractMRZRequest(ExtractMRZRequest value) {
        return new JAXBElement<ExtractMRZRequest>(_ExtractMRZRequest_QNAME, ExtractMRZRequest.class, null, value);
    }

}
